# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OBSSHackathon' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OBSSHackathon
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'IQKeyboardManager'

  target 'OBSSHackathonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OBSSHackathonUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
